# Generated by Django 3.0.6 on 2020-05-07 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du contrat')),
                ('points', models.IntegerField(verbose_name="Points à réaliser par l'attaque")),
                ('coefficient', models.IntegerField(verbose_name='Coefficient multiplicateur')),
            ],
        ),
        migrations.CreateModel(
            name='Couleur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=8, verbose_name='couleur')),
            ],
        ),
        migrations.CreateModel(
            name='Poignée',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TarotGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(default=False)),
                ('tours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TarotPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('prises_totales', models.IntegerField()),
                ('prise_petite', models.IntegerField()),
                ('prise_garde', models.IntegerField()),
                ('prise_garde_sans', models.IntegerField()),
                ('prise_garde_contre', models.IntegerField()),
                ('nombre_de_fois_appelé', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TarotTurn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='Numéro du tour')),
                ('petit', models.BooleanField(default=False, verbose_name='Petit au bout')),
                ('contrat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='compteur.Contrat')),
                ('couleur_appelée', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='compteur.Couleur')),
                ('défense', models.ManyToManyField(to='compteur.TarotPlayer', verbose_name='Liste des défenseurs')),
                ('joueur_appelé', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nom_appelé', to='compteur.TarotPlayer', verbose_name='Nom du joueur appelé')),
                ('joueur_preneur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nom_preneur', to='compteur.TarotPlayer', verbose_name='Nom du preneur')),
                ('partie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compteur.TarotGame')),
                ('poignée', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='compteur.Poignée')),
            ],
        ),
        migrations.AddField(
            model_name='tarotgame',
            name='players',
            field=models.ManyToManyField(to='compteur.TarotPlayer'),
        ),
    ]
